"""
Django settings for gd_cripto project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# BASE_DIR aponta para a raiz do projeto e evita caminhos absolutos espalhados.
BASE_DIR = Path(__file__).resolve().parent.parent


# Configurações rápidas de desenvolvimento.
# Em produção, SECRET_KEY deve vir de variável de ambiente e DEBUG deve ser False.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Lista de domínios/IPs autorizados a servir o projeto quando DEBUG=False.
ALLOWED_HOSTS = []


# Aplicações Django carregadas no projeto.
# As entradas django.contrib são recursos nativos; cripto_monitor é o app do GDH Cripto.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cripto_monitor',
]

# Middlewares rodam em ordem a cada requisição/resposta.
# Aqui ficam segurança, sessão, autenticação, mensagens e proteção CSRF.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Arquivo principal de rotas do projeto.
ROOT_URLCONF = 'gd_cripto.urls'

# Configuração dos templates HTML.
# APP_DIRS=True permite encontrar arquivos em templates/ dentro de cada app.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Entrada WSGI usada por servidores web em deploy tradicional.
WSGI_APPLICATION = 'gd_cripto.wsgi.application'


# Banco de dados.
# O projeto usa SQLite local, suficiente para desenvolvimento e testes simples.
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Espera locks transitórios passarem antes de falhar com "database is locked".
            'timeout': 20,
        },
    }
}


# Validadores de senha padrão do Django para usuários do sistema.
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Idioma, fuso e suporte a internacionalização.
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Arquivos estáticos: CSS, JavaScript, imagens e logo do sistema.
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Tipo padrão das chaves primárias criadas pelo Django.
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Para onde o usuário vai depois de entrar ou sair do sistema.
LOGIN_REDIRECT_URL = 'cripto_monitor:dashboard'
LOGOUT_REDIRECT_URL = 'login'
