# Generated by Django 5.2.15 on 2026-06-03 23:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=20)),
                ('coingecko_id', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('last_price_brl', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('last_price_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True)),
                ('last_change_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_price_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('above', 'Atingir acima de'), ('below', 'Atingir abaixo de')], max_length=8)),
                ('threshold_brl', models.DecimalField(decimal_places=6, max_digits=22)),
                ('active', models.BooleanField(default=True)),
                ('triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='cripto_monitor.cryptoasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_brl', models.DecimalField(decimal_places=6, max_digits=22)),
                ('price_usd', models.DecimalField(decimal_places=6, max_digits=22)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='coingecko', max_length=80)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cripto_monitor.cryptoasset')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invested_amount_brl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('buy_date', models.DateField()),
                ('purchased_price_brl', models.DecimalField(decimal_places=6, max_digits=22)),
                ('crypto_amount', models.DecimalField(decimal_places=12, max_digits=22)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='cripto_monitor.cryptoasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('BUY', 'Compra simulada'), ('SELL', 'Venda simulada')], max_length=8)),
                ('amount_brl', models.DecimalField(decimal_places=2, max_digits=18)),
                ('crypto_amount', models.DecimalField(decimal_places=12, max_digits=22)),
                ('price_brl', models.DecimalField(decimal_places=6, max_digits=22)),
                ('trade_date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='cripto_monitor.simulation')),
            ],
            options={
                'ordering': ['-trade_date', '-created_at'],
            },
        ),
    ]
